    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">



      <div class="container">



        <div class="navbar-header">



          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">



            <span class="sr-only">Toggle navigation</span>



            <span class="icon-bar"></span>



            <span class="icon-bar"></span>



            <span class="icon-bar"></span>



          </button>




        


        </div>



        <div id="navbar" class="navbar-collapse collapse">
<ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="index.php">Rapbot</a></li>

	  <li><a class="navbar-brand" href="goal.php">Our Goal</a></li>
<li class="dropdown">
	  <li><a class="navbar-brand" href="youtube.php">Concept Video</a></li>
<li class="dropdown">
          <li><a href="#" class="dropdown-toggle navbar-brand" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Team Members <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Jessica Freeze</a></li>
            <li><a href="#">Yennifer Hernandez</a></li>
            <li><a href="#">Hayden Freeman</a></li>
            <li><a href="#">Bilal Moiz</a></li>
            <li><a href="#">Garrett Sweeney</a></li>
            <li><a href="#">Zachary Teicher</a></li>
          </ul>
</li>
<li><a class="navbar-brand" href="funny.php">Check This Out</a></li>
</ul>



        </div><!--/.navbar-collapse -->



      </div>



    </nav>